# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybb', '0007_auto_20161125_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumsubscription',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Być informowany tylko kiedy zostanie dodany nowy temat.'), (2, 'Automatycznie subskrybować tematy.')], help_text="The auto-subscription works like you manually subscribed to watch each topic :\nyou will be notified when a topic will receive an answer. \nIf you choose to be notified only when a new topic is added. It meansyou will be notified only once when the topic is created : you won't be notified for the answers.", verbose_name='Subscription type'),
        ),
    ]
