# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Poradnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=150)),
                ('tresc', models.TextField()),
                ('kategoria', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tutorials.Kategoria')),
            ],
        ),
    ]
