# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoria',
            name='opis',
            field=models.TextField(default='-- Brak opisu --'),
        ),
    ]
