# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_poradnik_opis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widziany', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='poradnik',
            name='version',
            field=models.CharField(choices=[('P2', 'Python 2.7'), ('P3', 'Python 3.5'), ('PP', 'Python 2.7 and 3.5')], default='PP', max_length=2),
        ),
        migrations.AddField(
            model_name='visited',
            name='poradnik',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tutorials.Poradnik'),
        ),
    ]
