# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tutorials.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_auto_20161129_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=tutorials.models.Image.upload_location)),
                ('poradnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Poradnik')),
            ],
        ),
    ]
