# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='nazwa',
            field=models.CharField(default='', max_length=40),
        ),
    ]
