# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20161108_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=user.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='width_field',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
