# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20161113_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forgot_pass_expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='forgot_pass_key',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
